### ISSUE TITLE
Issues with the composer repo

### ISSUE THREAD

**Issue by IbrahimS2** [swissup/module-speculation-rules#3]
![image](https://github.com/user-attachments/assets/8e5bf574-ddcb-4813-a482-720cea61d253)

**Comment by 0m3r** [comment]
I see the 1.0.3 version of the package in both package repositories.
https://docs.swissuplabs.com/packages/#swissup/module-speculation-rules
https://packagist.org/packages/swissup/module-speculation-rules

Composer might cache package information, and outdated cache data could cause this warning. I think you need to update the composer cache.
```
composer clear-cache
```
And after run composer install or composer update again.

Another way 
Composer might use the public repository instead of the private one due to incorrect repository priority.
Set the priority for the private repository in composer.json:
```json
"repositories": [
    {
        "type": "composer",
        "url": "https://ci.swissuplabs.com/api/packages.json",
        "canonical": true
    }
]
```
Or you can exclude the public repository for this package, if necessary:
```json
"repositories": [
    {
        "type": "composer",
        "url": "https://packagist.org",
        "exclude": ["swissup/module-speculation-rules"]
    }
]

```

**Comment by IbrahimS2** [comment]
@0m3r It was updated only yesterday, so this is no longer an issue.
